name = "LatticeDiracOperators"
uuid = "019239df-b0e3-486e-8e4c-d1c29ee5d6b9"
authors = ["Akio Tomiya, Yuki Nagai <cometscome@gmail.com> and contributors"]
version = "0.3.0"

[deps]
AlgRemez_jll = "acb6dc63-88f0-54c7-a126-ccdc963b8b3f"
Gaugefields = "a461e10c-0d91-493e-bc41-027b226eee91"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Wilsonloop = "f3c8d4fe-2f22-401d-8228-e6a01d7a1d02"

[compat]
JLD2 = "0.4,0.5"
Requires = "1"
Wilsonloop = "0.1.5"
Gaugefields  = "0.2,0.3"
julia = "1.10"
SparseArrays = "1,2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
